name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.30'  
        extensions: mbstring, bcmath, pdo_mysql, exif
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install system dependencies
      run: sudo apt-get install -y libzip-dev zip unzip

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Copy .env example
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Seed the database
      run: php artisan db:seed --force

    - name: Run tests
      run: php artisan test

    - name: Display Composer logs for debugging
      if: failure()
      run: cat ${{ steps.composer-cache.outputs.dir }}/composer.log

    - name: Show installed PHP extensions for debugging
      if: failure()
      run: php -m
